version: '3.6'
services:
    php:
        image: 'php:apache'
        volumes:
            - './:/var/www/html'
        ports: 
            - 8000:80
        tty: true
    composer:
        image: 'composer:1.8'
        command: 
            - install
            - dump-autoload -o
        volumes:
            - './:/app'